"""upgrade login_check

Revision ID: 257028e58894
Revises: 28b4461b0ba1
Create Date: 2019-09-04 18:35:52.964772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257028e58894'
down_revision = '28b4461b0ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
